monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
                max_files: 2
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: rotate
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            deprecation:
                type: rotating_file
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecation_%kernel.environment%.log"
                max_files: 2
            rotate:
                type: rotating_file
                level: error
                #formatter: monolog.formatter.line
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                max_files: 10
#            nested:
#                type: stream
#                path: "%kernel.logs_dir%/%kernel.environment%.log"
#                level: debug
#                formatter: monolog.formatter.line
#            console:
#                type: console
#                process_psr_3_messages: false
#                channels: ["!event", "!doctrine"]
#            deprecation:
#                type: stream
#                channels: [deprecation]
#                path: "%kernel.logs_dir%/%kernel.environment%-deprecation.log"
#                formatter: monolog.formatter.line
