services:
    mariadb:
        container_name: bolao-mariadb
        image: mariadb:12.1.1-ubi10-rc
        working_dir: /app
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=bolao
            - MARIADB_DATABASE=bolao
            - MARIADB_USER=bolao
            - MARIADB_PASSWORD=bolao
        volumes:
            - type: volume
              source: mariadb
              target: /var/lib/mysql
            - .:/app
            
    phpmyadmin:
        container_name: bolao-phpmyadmin
        image: phpmyadmin:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=bolao
            - MYSQL_USER=bolao
            - MYSQL_PASSWORD=bolao
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=bolao
            - PMA_PASSWORD=bolao
            - PMA_PMADB=bolao
#            - PMA_ARBITRARY=0
        ports:
            - 8080:80
        depends_on:
            - mariadb
        links:
            - mariadb:db
            
    php-fpm:
        container_name: bolao-php-fpm
        build: 
            context: docker
            dockerfile: Dockerfile-php-fpm
        restart: always
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - 9000:9000
        depends_on:
            - nginx
            - mariadb
            - mail
            - redis            
            
    nginx:
        container_name: bolao-nginx
        image: nginx:1.29.1-alpine
        restart: always
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        environment:
            - NGINX_HOST=bolao.local.paginaemconstrucao.com.br
            - NGINX_PORT=80
            
    mail:
        container_name: bolao-mail
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - 8025:8025
            - 1025:1025
    
    redis:
        container_name: bolao-redis
        image: redis:8.2.1-alpine
        restart: always
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
            
    redisinsight:
        container_name: bolao-redisinsight
        image: redis/redisinsight:latest
        restart: always
        ports:
          - "5540:5540"
        depends_on:
          - redis
        volumes:
          - redisinsight_data:/data

volumes:
    mariadb:
    redis_data:
    redisinsight_data:
