-- MySQL Script generated by MySQL Workbench
-- Thu Sep  4 19:38:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bolao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bolao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bolao` DEFAULT CHARACTER SET utf8mb4 ;
USE `bolao` ;

-- -----------------------------------------------------
-- Table `bolao`.`loteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao`.`loteria` (
  `id` INT NOT NULL,
  `uuid` BINARY(16) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `url_slug` VARCHAR(60) NOT NULL,
  `url_api` VARCHAR(2048) NOT NULL,
  `dezenas` LONGTEXT NOT NULL,
  `apostas` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `url_slug_UNIQUE` (`url_slug` ASC),
  UNIQUE INDEX `url_api_UNIQUE` (`url_api` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `roles` LONGTEXT NOT NULL DEFAULT '[\"ROLE_USER\",\"ROLE_ADMIN\"]',
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
