FROM php:8.3.26-fpm-alpine3.22

RUN apk update

RUN apk add --no-cache --virtual .build-deps icu-dev zlib-dev libpng-dev libjpeg-turbo-dev freetype-dev oniguruma-dev $PHPIZE_DEPS

RUN pecl install redis

RUN docker-php-ext-enable redis

RUN docker-php-ext-install -j$(nproc) intl pdo pdo_mysql gd mbstring

RUN apk del .build-deps

WORKDIR /app