name: "Tux"

on:
  push: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: "Obter o código"
        uses: actions/checkout@v4
      - name: "Cache npm"
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: "Instalar dependências NPM"
        run: npm install
      - name: "Copiar código"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/deploy/bolao"
      - name: "Construção da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /deploy/bolao
            cp /deploy/config/bolao.env.prod.local /deploy/bolao/.env.prod.local
            APP_ENV=prod composer install --no-progress --prefer-dist --no-dev -a -o
            composer dump-env prod
            composer code:ci
            sudo -u www-data cp -RTf /deploy/bolao/ /var/www/bolao
