name: "Tux"

on:
  push: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: "Obter o código"
        uses: actions/checkout@v4
      - name: "Copiar código"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/deploy/bolao"
      - name: "Construção da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /deploy/bolao            
            composer install --no-dev --no-progress -a -o
            composer code:ci
            composer dump-env prod
            APP_ENV=prod php bin/console cache:warmup
            sudo cp -RTf /deploy/bolao/ /var/www/bolao
            cd /var/www/bolao
            sudo chown -R www-data: .
